language: python
python: 3.6
sudo: required

env:
- PYTHONUNBUFFERED=1

services:
- docker

# TODO(cutwater): Do we need this?
# before_install:
# - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
# - sudo apt-get update -qq

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - docker build -t dinivas/ansible-galaxy .
  - docker push dinivas/ansible-galaxy

env:
  global:
    - GH_REF: github.com/dinivas/dinivas.git
