# Generated by Django 2.1.7 on 2019-09-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0143_collection_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='provider_api_token',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
